// Константы разрешений

export const PERMISSIONS = {
  // Рекламодатели
  VIEW_ADVERTISERS: 'view_advertisers',
  CREATE_ADVERTISER: 'create_advertiser',
  EDIT_ADVERTISER: 'edit_advertiser',
  DELETE_ADVERTISER: 'delete_advertiser',
  MANAGE_ADVERTISER_BUDGET: 'manage_advertiser_budget',

  // Рекламные кампании
  VIEW_CAMPAIGNS: 'view_campaigns',
  CREATE_CAMPAIGN: 'create_campaign',
  EDIT_CAMPAIGN: 'edit_campaign',
  DELETE_CAMPAIGN: 'delete_campaign',
  CHANGE_CAMPAIGN_STATUS: 'change_campaign_status',

  // Группы объявлений
  VIEW_ADGROUPS: 'view_adgroups',
  CREATE_ADGROUP: 'create_adgroup',
  EDIT_ADGROUP: 'edit_adgroup',
  DELETE_ADGROUP: 'delete_adgroup',
  CHANGE_ADGROUP_STATUS: 'change_adgroup_status',

  // Креативы
  VIEW_CREATIVES: 'view_creatives',
  CREATE_CREATIVE: 'create_creative',
  EDIT_CREATIVE: 'edit_creative',
  DELETE_CREATIVE: 'delete_creative',
  CHANGE_CREATIVE_STATUS: 'change_creative_status',

  // Статистика и отчеты
  VIEW_STATISTICS: 'view_statistics',
  EXPORT_REPORTS: 'export_reports',
} as const

// Роли и их разрешения
export const ROLE_PERMISSIONS = {
  employee_admin: [
    // Полный доступ ко всему
    PERMISSIONS.VIEW_ADVERTISERS,
    PERMISSIONS.CREATE_ADVERTISER,
    PERMISSIONS.EDIT_ADVERTISER,
    PERMISSIONS.DELETE_ADVERTISER,
    PERMISSIONS.MANAGE_ADVERTISER_BUDGET,
    PERMISSIONS.VIEW_CAMPAIGNS,
    PERMISSIONS.CREATE_CAMPAIGN,
    PERMISSIONS.EDIT_CAMPAIGN,
    PERMISSIONS.DELETE_CAMPAIGN,
    PERMISSIONS.CHANGE_CAMPAIGN_STATUS,
    PERMISSIONS.VIEW_ADGROUPS,
    PERMISSIONS.CREATE_ADGROUP,
    PERMISSIONS.EDIT_ADGROUP,
    PERMISSIONS.DELETE_ADGROUP,
    PERMISSIONS.CHANGE_ADGROUP_STATUS,
    PERMISSIONS.VIEW_CREATIVES,
    PERMISSIONS.CREATE_CREATIVE,
    PERMISSIONS.EDIT_CREATIVE,
    PERMISSIONS.DELETE_CREATIVE,
    PERMISSIONS.CHANGE_CREATIVE_STATUS,
    PERMISSIONS.VIEW_STATISTICS,
    PERMISSIONS.EXPORT_REPORTS,
  ],

  employee_traffic: [
    // Доступ к кампаниям и статистике, без изменения данных рекламодателя
    PERMISSIONS.VIEW_ADVERTISERS,
    PERMISSIONS.VIEW_CAMPAIGNS,
    PERMISSIONS.CREATE_CAMPAIGN,
    PERMISSIONS.EDIT_CAMPAIGN,
    PERMISSIONS.DELETE_CAMPAIGN,
    PERMISSIONS.CHANGE_CAMPAIGN_STATUS,
    PERMISSIONS.VIEW_ADGROUPS,
    PERMISSIONS.CREATE_ADGROUP,
    PERMISSIONS.EDIT_ADGROUP,
    PERMISSIONS.DELETE_ADGROUP,
    PERMISSIONS.CHANGE_ADGROUP_STATUS,
    PERMISSIONS.VIEW_CREATIVES,
    PERMISSIONS.CREATE_CREATIVE,
    PERMISSIONS.EDIT_CREATIVE,
    PERMISSIONS.DELETE_CREATIVE,
    PERMISSIONS.CHANGE_CREATIVE_STATUS,
    PERMISSIONS.VIEW_STATISTICS,
    PERMISSIONS.EXPORT_REPORTS,
  ],

  advertiser_admin: [
    // Доступ к своим данным и кампаниям, но не к бюджету
    PERMISSIONS.VIEW_ADVERTISERS,
    PERMISSIONS.EDIT_ADVERTISER,
    PERMISSIONS.VIEW_CAMPAIGNS,
    PERMISSIONS.CREATE_CAMPAIGN,
    PERMISSIONS.EDIT_CAMPAIGN,
    PERMISSIONS.DELETE_CAMPAIGN,
    PERMISSIONS.CHANGE_CAMPAIGN_STATUS,
    PERMISSIONS.VIEW_ADGROUPS,
    PERMISSIONS.CREATE_ADGROUP,
    PERMISSIONS.EDIT_ADGROUP,
    PERMISSIONS.DELETE_ADGROUP,
    PERMISSIONS.CHANGE_ADGROUP_STATUS,
    PERMISSIONS.VIEW_CREATIVES,
    PERMISSIONS.CREATE_CREATIVE,
    PERMISSIONS.EDIT_CREATIVE,
    PERMISSIONS.DELETE_CREATIVE,
    PERMISSIONS.CHANGE_CREATIVE_STATUS,
    PERMISSIONS.VIEW_STATISTICS,
    PERMISSIONS.EXPORT_REPORTS,
  ],

  advertiser_traffic: [
    // Только просмотр и работа с кампаниями
    PERMISSIONS.VIEW_ADVERTISERS,
    PERMISSIONS.VIEW_CAMPAIGNS,
    PERMISSIONS.CREATE_CAMPAIGN,
    PERMISSIONS.EDIT_CAMPAIGN,
    PERMISSIONS.DELETE_CAMPAIGN,
    PERMISSIONS.CHANGE_CAMPAIGN_STATUS,
    PERMISSIONS.VIEW_ADGROUPS,
    PERMISSIONS.CREATE_ADGROUP,
    PERMISSIONS.EDIT_ADGROUP,
    PERMISSIONS.DELETE_ADGROUP,
    PERMISSIONS.CHANGE_ADGROUP_STATUS,
    PERMISSIONS.VIEW_CREATIVES,
    PERMISSIONS.CREATE_CREATIVE,
    PERMISSIONS.EDIT_CREATIVE,
    PERMISSIONS.DELETE_CREATIVE,
    PERMISSIONS.CHANGE_CREATIVE_STATUS,
    PERMISSIONS.VIEW_STATISTICS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
} as const
