import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'en' | 'ru'

interface LanguageState {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, fallback?: string) => string
}

// Переводы (технические термины оставляем на английском)
const translations = {
  en: {
    // Navigation
    'nav.main': 'Main',
    'nav.segments': 'Segments',
    'nav.dsp_analytics': 'DSP Analytics',
    'nav.advertisers': 'Advertisers',
    'nav.adgroups': 'Ad Groups',
    'nav.analytics': 'Analytics',
    'nav.fraud_detection': 'Fraud Detection',
    'nav.audience_insights': 'Audience Insights', 
    'nav.creative_performance': 'Creative Performance',
    'nav.campaigns': 'Campaigns',
    'nav.audiences': 'Audiences',
    'nav.creatives': 'Creatives',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    
    // Headers
    'header.dsp_analytics': 'DSP Analytics',
    'header.campaign_management': 'Campaign Management',
    'header.audience_insights': 'Audience Insights',
    'header.fraud_detection': 'Fraud Detection',
    'header.real_time': 'Real-time',
    'header.dsp_manager': 'DSP Manager',
    
    // Analytics Page
    'analytics.title': 'DSP Performance Dashboard',
    'analytics.total_impressions': 'Total Impressions',
    'analytics.total_clicks': 'Total Clicks',
    'analytics.average_ctr': 'Average CTR',
    'analytics.vs_last_week': 'vs last week',
    'analytics.device_performance': 'Device Performance',
    'analytics.top_regions': 'Top Regions',
    'analytics.real_time_bidding': 'Real-time Bidding',
    'analytics.bids_per_sec': 'Bids/sec',
    'analytics.win_rate': 'Win Rate %',
    'analytics.avg_price': 'Avg Price',
    'analytics.dsp_performance_metrics': 'DSP Performance Metrics',
    'analytics.campaign_team': 'Campaign Team',
    'analytics.active_campaigns_performance': 'Active Campaigns Performance',
    'analytics.export': 'Export',
    'analytics.status': 'Status',
    'analytics.impressions': 'Impressions',
    'analytics.clicks': 'Clicks',
    'analytics.conversions': 'Conversions',
    'analytics.spend': 'Spend',
    'analytics.active': 'Active',
    'analytics.paused': 'Paused',
    
    // Fraud Detection
    'fraud.title': 'Fraud Detection Center',
    'fraud.subtitle': 'Real-time traffic quality monitoring',
    'fraud.fraud_rate': 'Fraud Rate',
    'fraud.blocked_traffic': 'Blocked Traffic',
    'fraud.suspicious_ips': 'Suspicious IPs',
    'fraud.bot_traffic': 'Bot Traffic',
    'fraud.vs_yesterday': 'vs yesterday',
    'fraud.real_time_threats': 'Real-time Threats',
    'fraud.geographic_risk': 'Geographic Risk',
    'fraud.detection_methods': 'Detection Methods',
    'fraud.fraud_detection_log': 'Fraud Detection Log',
    'fraud.export_report': 'Export Report',
    'fraud.timestamp': 'Timestamp',
    'fraud.threat_type': 'Threat Type',
    'fraud.source_ip': 'Source IP',
    'fraud.campaign': 'Campaign',
    'fraud.severity': 'Severity',
    'fraud.action': 'Action',
    'fraud.status': 'Status',
    'fraud.high': 'High',
    'fraud.medium': 'Medium',
    'fraud.low': 'Low',
    'fraud.blocked': 'Blocked',
    'fraud.flagged': 'Flagged',
    'fraud.logged': 'Logged',
    'fraud.resolved': 'Resolved',
    'fraud.monitoring': 'Monitoring',
    'fraud.reviewed': 'Reviewed',
    
    // Audience Insights
    'audience.title': 'Audience Insights',
    'audience.subtitle': 'Deep audience analysis and segmentation',
    'audience.all_segments': 'All Segments',
    'audience.create_segment': 'Create Segment',
    'audience.high_value_customers': 'High-Value Customers',
    'audience.lookalike_audience': 'Lookalike Audience',
    'audience.retargeting_pool': 'Retargeting Pool',
    'audience.interest_based': 'Interest-Based',
    'audience.growth': 'Growth',
    'audience.conv_rate': 'Conv Rate',
    'audience.demographics': 'Demographics',
    'audience.age_groups': 'Age Groups',
    'audience.gender_split': 'Gender Split',
    'audience.female': 'Female',
    'audience.male': 'Male',
    'audience.top_interests': 'Top Interests',
    'audience.device_usage': 'Device Usage',
    'audience.devices': 'Devices',
    'audience.high_engagement': 'High engagement',
    'audience.medium_engagement': 'Medium engagement',
    'audience.low_engagement': 'Low engagement',
    'audience.operating_systems': 'Operating Systems',
    'audience.purchase_intent_analysis': 'Purchase Intent Analysis',
    'audience.average_intent_score': 'Average Intent Score',
    'audience.lookalike_performance': 'Lookalike Performance',
    'audience.quality_score': 'Quality Score',
    
    // Creative Performance
    'creative.title': 'Creative Performance',
    'creative.subtitle': 'Analyze and optimize creative assets',
    'creative.all_formats': 'All Formats',
    'creative.banner': 'Banner',
    'creative.video': 'Video',
    'creative.native': 'Native',
    'creative.display': 'Display',
    'creative.upload_creative': 'Upload Creative',
    'creative.create_new': 'Create Creative',
    'creative.total_creatives': 'Total Creatives',
    'creative.active': 'Active',
    'creative.avg_ctr': 'Avg CTR',
    'creative.top_ctr': 'Top CTR',
    'creative.avg_conv_rate': 'Avg Conv Rate',
    'creative.this_week': 'this week',
    'creative.of_total': 'of total',
    'creative.improvement': 'improvement',
    'creative.vs_last_month': 'vs last month',
    'creative.video_format': 'Video format',
    'creative.format_performance': 'Format Performance',
    'creative.active_ab_tests': 'Active A/B Tests',
    'creative.creative_assets': 'Creative Assets',
    'creative.export': 'Export',
    'creative.type': 'Type',
    'creative.performance': 'Performance',
    'creative.high': 'High',
    'creative.medium': 'Medium',
    'creative.low': 'Low',
    'creative.confidence': 'confidence',
    'creative.winner': 'Winner',
    
    // Common
    'common.campaign': 'Campaign',
    'common.campaigns': 'Campaigns',
    'common.name': 'Name',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.paused': 'Paused',
    'common.share': 'share',
    'common.engagement': 'engagement',
    'common.baseline': 'Baseline',
    'common.updated': 'Updated',
    'common.ago': 'ago',
    'common.min_ago': 'min ago',
    'common.day_ago': 'day ago',
    'common.vs': 'vs',
    'common.target': 'Target',
    'common.current': 'Current',
    'common.last_week': 'Last Week',
    'common.users': 'users',
    'common.impressions': 'impressions',
    'common.of_fraud': 'of fraud',
    'common.learning': 'Learning',
    'common.accuracy': 'Accuracy',
    
    // Settings
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.notifications': 'Notifications',
    'settings.profile': 'Profile',
    'settings.logout': 'Logout',
    'settings.english': 'English',
    'settings.russian': 'Русский',
    
    // Time ranges
    'time.1h': '1h',
    'time.6h': '6h', 
    'time.24h': '24h',
    'time.7d': '7d',
    'time.30d': '30d',
    'time.90d': '90d',
    
    // Metrics
    'metric.impressions': 'Impressions',
    'metric.clicks': 'Clicks',
    'metric.ctr': 'CTR',
    'metric.spend': 'Spend',
    'metric.cpm': 'CPM',
    'metric.budget': 'Budget',
    'metric.conversions': 'Conversions',
    'metric.revenue': 'Revenue',
    
    // Status
    'status.active': 'Active',
    'status.paused': 'Paused',
    'status.completed': 'Completed',
    'status.draft': 'Draft',
    
    // Campaign actions
    'campaign.create_new': 'Create Campaign',
    'campaign.manage_campaigns': 'Manage Campaigns',
    'campaign.all_campaigns': 'All Campaigns',
    'campaign.view_details': 'View Details',
    'campaign.edit': 'Edit',
    'campaign.copy': 'Copy',
    'campaign.pause': 'Pause',
    'campaign.resume': 'Resume',
    
    // Advertiser actions
    'advertiser.create_new': 'Create Advertiser',
    'advertiser.manage_advertisers': 'Manage Advertisers',
    'advertiser.all_advertisers': 'All Advertisers',
    'advertiser.view_campaigns': 'View Campaigns',
    
    // Form fields
    'form.name': 'Name',
    'form.budget': 'Budget',
    'form.status': 'Status',
    'form.start_date': 'Start Date',
    'form.end_date': 'End Date',
    'form.description': 'Description',
    'form.save': 'Save',
    'form.cancel': 'Cancel',
    'form.create': 'Create',
    'form.update': 'Update',
    
    // Campaign form
    'form.campaign_name': 'Campaign Name',
    'form.enter_campaign_name': 'Enter campaign name',
    'form.campaign_period': 'Campaign Period',
    'form.from': 'From',
    'form.to': 'To',
    'form.platform': 'Platform',
    'form.select_platform': 'Select platform',
    'form.user_frequency_limit': 'User Frequency Limit',
    'form.ad_frequency_limit': 'Ad Frequency Limit',
    'form.click_limit': 'Click Limit',
    'form.shows': 'Shows',
    
    // Ad Group form
    'form.placement_name': 'Placement Name',
    'form.adgroup_name': 'Ad Group Name',
    'form.time_range': 'Time Range',
    'form.user_show_limit': 'User Show Limit',
    'form.ad_show_limit': 'Ad Show Limit',
    'form.transition_limit': 'Transition Limit',
    'form.ready_segment': 'Ready Segment',
    'form.upload_csv': 'Upload CSV file to load a new segment',
    'form.exclude_audience': 'Exclude Audience',
    'form.phone_model': 'Phone Model',
    'form.region': 'Region',
    'form.os_language': 'OS Language',
    'form.os_version': 'OS Version',
    'form.interests': 'Interests',
    'form.show_dates': 'Campaign Period',
    'form.show_time': 'Show Time',
    'form.exclude_segments': 'Exclude Audience',
    'form.exclude_regions': 'Exclude Regions',
    'form.ad_groups': 'Ad Groups',
    'form.all_day': 'All Day',
    
    // Creative form
    'form.placement': 'Placement',
    'form.creative_name': 'Creative Name',
    'form.creative_budget': 'Creative Budget',
    'form.creative_title': 'Creative Title',
    'form.creative_text': 'Creative Text',
    'form.enter_title': 'Enter title',
    'form.enter_text': 'Enter text',
    'form.enter_link': 'Enter link',
    'form.max_16_chars': 'Maximum 16 characters',
    'form.max_32_chars': 'Maximum 32 characters',
    'form.image': 'Image',
    'form.upload_image': 'Upload image file for loading, no larger than 1920x1080 pixels',
    'form.image_sizes': 'Image sizes 1200x675, 1080x608, 600x324 pixels',
    'form.cpm': 'CPM',
    'form.preview': 'Preview',
    'form.launch_after_save': 'Launch after save',
    
    // Advertiser form
    'form.advertiser_name': 'Advertiser Name',
    'form.legal_name': 'Legal Name',
    'form.inn': 'INN',
    'form.kpp': 'KPP',
    'form.ogrn': 'OGRN/OGRNIP',
    'form.legal_address': 'Legal Address',
    'form.bik': 'BIK',
    'form.account_number': 'Account Number',
    'form.contract_number': 'Contract Number',
    'form.contract_date': 'Contract Date',
    'form.use_auto_marketing': 'Use auto-marketing in ORD',
    
    // Actions
    'action.edit': 'Edit',
    'action.copy': 'Copy',
    'action.delete': 'Delete',
    'action.view': 'View',
    'action.create': 'Create',
    'action.export': 'Export',
    'action.refresh': 'Refresh',
    'action.duplicate': 'Duplicate',
    'action.pause': 'Pause',
    'action.resume': 'Resume',
    
    // Messages
    'campaign.copied_successfully': 'Campaign copied successfully',
    'advertiser.copied_successfully': 'Advertiser copied successfully',
    'advertiser.created_successfully': 'Advertiser created successfully',
    'advertiser.updated_successfully': 'Advertiser updated successfully',
    'advertiser.deleted_successfully': 'Advertiser deleted successfully',
    'campaign.created_successfully': 'Campaign created successfully',
    'campaign.updated_successfully': 'Campaign updated successfully', 
    'campaign.deleted_successfully': 'Campaign deleted successfully',
    'adgroup.created_successfully': 'Ad group created successfully',
    'adgroup.updated_successfully': 'Ad group updated successfully',
    'adgroup.deleted_successfully': 'Ad group deleted successfully',
    'creative.created_successfully': 'Creative created successfully',
    'creative.updated_successfully': 'Creative updated successfully',
    'creative.deleted_successfully': 'Creative deleted successfully',
    
    // Validation
    'form.required_field': 'This field is required',
    'form.invalid_inn': 'INN must be 12 digits',
    'form.invalid_kpp': 'KPP must be 9 digits',
    'form.invalid_ogrn': 'OGRN must be 15 digits',
    'form.invalid_bik': 'BIK must be 9 digits',
    'form.invalid_account': 'Account number must be 20 digits',
    'form.validation_error': 'Please fix validation errors',
    'form.enter_advertiser_name': 'Enter advertiser name',
    'form.enter_legal_name': 'Enter legal name',
    'form.enter_contract_number': 'Enter contract number',
    'form.enter_legal_address': 'Enter legal address',
    'form.enter_description': 'Enter description',
    'form.enter_adgroup_name': 'Enter ad group name',
    'form.enter_creative_title': 'Where is better to hang out...',
    'form.enter_creative_text': 'Kilograms of money just like that...',
    'form.period': 'Period',
    'form.creative_notice': 'Please note that all created ads will be reviewed by moderation.',
    'form.note_creative': 'Creative Guidelines',
    'form.creative_requirements': 'All creative materials will be reviewed according to our quality standards.',
    'form.small_format_desc': 'Small format for compact placement',
    'form.big_format_desc': 'Large format for maximum visibility',
    'form.ad_groups': 'Ad Groups',
    'form.all_day': 'All Day',
    'action.exit': 'Exit',
    
    // Time periods
    'time.day': 'Day',
    'time.week': 'Week', 
    'time.month': 'Month',
    'time.whole_campaign': 'Whole campaign',
    
    // Additional statuses
    'status.pending': 'Pending',
    'status.rejected': 'Rejected',
    
    // Additional UI elements
    'nav.statistics': 'Statistics',
    'ui.all_formats': 'All formats',
    'ui.upload_creative': 'Upload Creative',
    'ui.grid_view': 'Grid View',
    'ui.chart_view': 'Chart View',
    'ui.toggle_view': 'Toggle between grid and chart view',
    'ui.filter': 'Filter',
    'ui.apply_filter': 'Apply filters to results',
    'ui.search': 'Search',
    'ui.export': 'Export data',
    'ui.refresh': 'Refresh data',
    'ui.view_all': 'View All',
    'ui.show_more': 'Show More',
    'ui.show_less': 'Show Less'
  },
  ru: {
    // Navigation
    'nav.main': 'Основные',
    'nav.segments': 'Сегменты',
    'nav.dsp_analytics': 'DSP Аналитика',
    'nav.advertisers': 'Рекламодатели',
    'nav.adgroups': 'Группы объявлений',
    'nav.analytics': 'Общая аналитика',
    'nav.fraud_detection': 'Детекция фрода',
    'nav.audience_insights': 'Анализ аудитории',
    'nav.creative_performance': 'Эффективность креативов',
    'nav.campaigns': 'Кампании',
    'nav.audiences': 'Аудитории',
    'nav.creatives': 'Креативы',
    'nav.reports': 'Отчёты',
    'nav.settings': 'Настройки',
    
    // Headers
    'header.dsp_analytics': 'DSP Аналитика',
    'header.campaign_management': 'Управление кампаниями',
    'header.audience_insights': 'Анализ аудитории',
    'header.fraud_detection': 'Детекция фрода',
    'header.real_time': 'Реальное время',
    'header.dsp_manager': 'DSP Менеджер',
    
    // Analytics Page
    'analytics.title': 'Панель эффективности DSP',
    'analytics.total_impressions': 'Всего показов',
    'analytics.total_clicks': 'Всего кликов',
    'analytics.average_ctr': 'Средний CTR',
    'analytics.vs_last_week': 'к прошлой неделе',
    'analytics.device_performance': 'Эффективность устройств',
    'analytics.top_regions': 'Топ регионы',
    'analytics.real_time_bidding': 'Биддинг в реальном времени',
    'analytics.bids_per_sec': 'Ставок/сек',
    'analytics.win_rate': 'Процент побед',
    'analytics.avg_price': 'Средняя цена',
    'analytics.dsp_performance_metrics': 'Метрики эффективности DSP',
    'analytics.campaign_team': 'Команда кампаний',
    'analytics.active_campaigns_performance': 'Эффективность активных кампаний',
    'analytics.export': 'Экспорт',
    'analytics.status': 'Статус',
    'analytics.impressions': 'Показы',
    'analytics.clicks': 'Клики',
    'analytics.conversions': 'Конверсии',
    'analytics.spend': 'Потрачено',
    'analytics.active': 'Активна',
    'analytics.paused': 'Приостановлена',
    
    // Fraud Detection
    'fraud.title': 'Центр детекции фрода',
    'fraud.subtitle': 'Мониторинг качества трафика в реальном времени',
    'fraud.fraud_rate': 'Доля фрода',
    'fraud.blocked_traffic': 'Заблокированный трафик',
    'fraud.suspicious_ips': 'Подозрительные IP',
    'fraud.bot_traffic': 'Ботовый трафик',
    'fraud.vs_yesterday': 'к вчерашнему дню',
    'fraud.real_time_threats': 'Угрозы в реальном времени',
    'fraud.geographic_risk': 'Географические риски',
    'fraud.detection_methods': 'Методы детекции',
    'fraud.fraud_detection_log': 'Журнал детекции фрода',
    'fraud.export_report': 'Экспорт отчёта',
    'fraud.timestamp': 'Время',
    'fraud.threat_type': 'Тип угрозы',
    'fraud.source_ip': 'Исходный IP',
    'fraud.campaign': 'Кампания',
    'fraud.severity': 'Серьёзность',
    'fraud.action': 'Действие',
    'fraud.status': 'Статус',
    'fraud.high': 'Высокий',
    'fraud.medium': 'Средний',
    'fraud.low': 'Низкий',
    'fraud.blocked': 'Заблокирован',
    'fraud.flagged': 'Отмечен',
    'fraud.logged': 'Записан',
    'fraud.resolved': 'Решён',
    'fraud.monitoring': 'Мониторинг',
    'fraud.reviewed': 'Проверен',
    
    // Audience Insights
    'audience.title': 'Анализ аудитории',
    'audience.subtitle': 'Глубокий анализ и сегментация аудитории',
    'audience.all_segments': 'Все сегменты',
    'audience.create_segment': 'Создать сегмент',
    'audience.high_value_customers': 'Высокоценные клиенты',
    'audience.lookalike_audience': 'Похожая аудитория',
    'audience.retargeting_pool': 'Пул ретаргетинга',
    'audience.interest_based': 'По интересам',
    'audience.growth': 'Рост',
    'audience.conv_rate': 'Конв. ставка',
    'audience.demographics': 'Демография',
    'audience.age_groups': 'Возрастные группы',
    'audience.gender_split': 'Распределение по полу',
    'audience.female': 'Женщины',
    'audience.male': 'Мужчины',
    'audience.top_interests': 'Топ интересы',
    'audience.device_usage': 'Использование устройств',
    'audience.devices': 'Устройства',
    'audience.high_engagement': 'Высокая активность',
    'audience.medium_engagement': 'Средняя активность',
    'audience.low_engagement': 'Низкая активность',
    'audience.operating_systems': 'Операционные системы',
    'audience.purchase_intent_analysis': 'Анализ намерений покупки',
    'audience.average_intent_score': 'Средний балл намерений',
    'audience.lookalike_performance': 'Эффективность похожих',
    'audience.quality_score': 'Оценка качества',
    
    // Creative Performance
    'creative.title': 'Эффективность креативов',
    'creative.subtitle': 'Анализ и оптимизация креативных материалов',
    'creative.all_formats': 'Все форматы',
    'creative.banner': 'Баннер',
    'creative.video': 'Видео',
    'creative.native': 'Нативная',
    'creative.display': 'Дисплей',
    'creative.upload_creative': 'Загрузить креатив',
    'creative.create_new': 'Создать креатив',
    'creative.total_creatives': 'Всего креативов',
    'creative.active': 'Активные',
    'creative.avg_ctr': 'Средний CTR',
    'creative.top_ctr': 'Лучший CTR',
    'creative.avg_conv_rate': 'Средняя конв. ставка',
    'creative.this_week': 'на этой неделе',
    'creative.of_total': 'от общего',
    'creative.improvement': 'улучшение',
    'creative.vs_last_month': 'к прошлому месяцу',
    'creative.video_format': 'Видео формат',
    'creative.format_performance': 'Эффективность форматов',
    'creative.active_ab_tests': 'Активные A/B тесты',
    'creative.creative_assets': 'Креативные материалы',
    'creative.export': 'Экспорт',
    'creative.type': 'Тип',
    'creative.performance': 'Эффективность',
    'creative.high': 'Высокая',
    'creative.medium': 'Средняя',
    'creative.low': 'Низкая',
    'creative.confidence': 'достоверность',
    'creative.winner': 'Победитель',
    
    // Common
    'common.campaign': 'Кампания',
    'common.campaigns': 'Кампании',
    'common.name': 'Название',
    'common.status': 'Статус',
    'common.active': 'Активна',
    'common.paused': 'Приостановлена',
    'common.share': 'доля',
    'common.engagement': 'активность',
    'common.baseline': 'Базовая линия',
    'common.updated': 'Обновлено',
    'common.ago': 'назад',
    'common.min_ago': 'мин назад',
    'common.day_ago': 'день назад',
    'common.vs': 'к',
    'common.target': 'Цель',
    'common.current': 'Текущий',
    'common.last_week': 'Прошлая неделя',
    'common.users': 'пользователи',
    'common.impressions': 'показы',
    'common.of_fraud': 'фрода',
    'common.learning': 'Обучение',
    'common.accuracy': 'Точность',
    
    // Settings
    'settings.language': 'Язык',
    'settings.theme': 'Тема',
    'settings.notifications': 'Уведомления',
    'settings.profile': 'Профиль',
    'settings.logout': 'Выйти',
    'settings.english': 'English',
    'settings.russian': 'Русский',
    
        // Time ranges
    'time.1h': '1ч',
    'time.6h': '6ч',
    'time.24h': '24ч',
    'time.7d': '7д',
    'time.30d': '30д',
    'time.90d': '90д',
    
    // Metrics
    'metric.impressions': 'Показы',
    'metric.clicks': 'Клики',
    'metric.ctr': 'CTR',
    'metric.spend': 'Потрачено',
    'metric.cpm': 'CPM',
    'metric.budget': 'Бюджет',
    'metric.conversions': 'Конверсии',
    'metric.revenue': 'Доход',
    
    // Status
    'status.active': 'Активна',
    'status.paused': 'Пауза',
    'status.completed': 'Завершена',
    'status.draft': 'Черновик',
    
    // Campaign actions
    'campaign.create_new': 'Создать кампанию',
    'campaign.manage_campaigns': 'Управление кампаниями',
    'campaign.all_campaigns': 'Все кампании',
    'campaign.view_details': 'Подробности',
    'campaign.edit': 'Редактировать',
    'campaign.copy': 'Копировать',
    'campaign.pause': 'Приостановить',
    'campaign.resume': 'Возобновить',
    
    // Advertiser actions
    'advertiser.create_new': 'Создать рекламодателя',
    'advertiser.manage_advertisers': 'Управление рекламодателями',
    'advertiser.all_advertisers': 'Все рекламодатели',
    'advertiser.view_campaigns': 'Посмотреть кампании',
    
    // Form fields
    'form.name': 'Название',
    'form.budget': 'Бюджет',
    'form.status': 'Статус',
    'form.start_date': 'Дата начала',
    'form.end_date': 'Дата окончания',
    'form.description': 'Описание',
    'form.save': 'Сохранить',
    'form.cancel': 'Отмена',
    'form.create': 'Создать',
    'form.update': 'Обновить',
    
    // Campaign form
    'form.campaign_name': 'Название кампании',
    'form.enter_campaign_name': 'Введите название кампании',
    'form.campaign_period': 'Период проведения кампании',
    'form.from': 'с',
    'form.to': 'до',
    'form.platform': 'Площадка размещения',
    'form.select_platform': 'Выберите площадку',
    'form.user_frequency_limit': 'Лимит показов на пользователя',
    'form.ad_frequency_limit': 'Лимит показов объявления',
    'form.click_limit': 'Лимит переходов',
    'form.shows': 'Показ',
    
    // Ad Group form
    'form.placement_name': 'Площадка размещения',
    'form.adgroup_name': 'Название группы объявлений',
    'form.time_range': 'Время показа',
    'form.user_show_limit': 'Лимит показов на пользователя',
    'form.ad_show_limit': 'Лимит показов объявления',
    'form.transition_limit': 'Лимит переходов',
    'form.ready_segment': 'Готовый сегмент',
    'form.upload_csv': 'Перетащите файл сюда, чтобы загрузить новый сегмент',
    'form.exclude_audience': 'Исключить аудиторию',
    'form.phone_model': 'Модель телефона',
    'form.region': 'Регион',
    'form.os_language': 'Язык ОС',
    'form.os_version': 'Версия ОС',
    'form.interests': 'Интересы',
    'form.show_dates': 'Интервал проведения РК',
    'form.show_time': 'Время показа',
    'form.exclude_segments': 'Исключить аудиторию',
    'form.exclude_regions': 'Исключить регионы',
    'form.ad_groups': 'Группы объявлений',
    'form.all_day': 'Весь день',
    
    // Creative form
    'form.placement': 'Плейсмент',
    'form.creative_name': 'Название креатива',
    'form.creative_budget': 'Бюджет креатива',
    'form.creative_title': 'Введите заголовок креатива',
    'form.creative_text': 'Введите текст креатива',
    'form.enter_title': 'Где лучше тусовать...',
    'form.enter_text': 'Килограммы денег просто так в ойтаучки...',
    'form.enter_link': 'Введите ссылку',
    'form.max_16_chars': 'Максимум 16 символов',
    'form.max_32_chars': 'Максимум 32 символа',
    'form.image': 'Изображение',
    'form.upload_image': 'Перетащите сюда изображение для загрузки или нажмите на кнопку чтобы выбрать в проводнике',
    'form.image_sizes': 'Размеры креативов 1200x675, 1080x608, 600x324 пикселей',
    'form.cpm': 'CPM',
    'form.preview': 'Предпросмотр',
    'form.launch_after_save': 'Запуск после сохранения',
    
    // Advertiser form
    'form.advertiser_name': 'Наименование рекламодателя',
    'form.legal_name': 'Наименование юр лица',
    'form.inn': 'ИНН',
    'form.kpp': 'КПП',
    'form.ogrn': 'ОГРН/ОГРНИП',
    'form.legal_address': 'Юридический адрес',
    'form.bik': 'БИК',
    'form.account_number': 'р/с',
    'form.contract_number': 'Номер договора',
    'form.contract_date': 'Дата заключения договора',
    'form.use_auto_marketing': 'Использовать автомаркировку в ОРД',
    
    // Actions
    'action.edit': 'Редактировать',
    'action.copy': 'Копировать',
    'action.delete': 'Удалить',
    'action.view': 'Посмотреть',
    'action.create': 'Создать',
    'action.export': 'Экспорт',
    'action.refresh': 'Обновить',
    'action.duplicate': 'Дублировать',
    'action.pause': 'Приостановить',
    'action.resume': 'Возобновить',
    
    // Messages
    'campaign.copied_successfully': 'Кампания скопирована успешно',
    'advertiser.copied_successfully': 'Рекламодатель скопирован успешно',
    'advertiser.created_successfully': 'Рекламодатель создан успешно',
    'advertiser.updated_successfully': 'Рекламодатель обновлен успешно',
    'advertiser.deleted_successfully': 'Рекламодатель удален успешно',
    'campaign.created_successfully': 'Кампания создана успешно',
    'campaign.updated_successfully': 'Кампания обновлена успешно',
    'campaign.deleted_successfully': 'Кампания удалена успешно',
    'adgroup.created_successfully': 'Группа объявлений создана успешно',
    'adgroup.updated_successfully': 'Группа объявлений обновлена успешно',
    'adgroup.deleted_successfully': 'Группа объявлений удалена успешно',
    'creative.created_successfully': 'Креатив создан успешно',
    'creative.updated_successfully': 'Креатив обновлен успешно',
    'creative.deleted_successfully': 'Креатив удален успешно',
    
    // Validation
    'form.required_field': 'Это поле обязательно',
    'form.invalid_inn': 'ИНН должен содержать 12 цифр',
    'form.invalid_kpp': 'КПП должен содержать 9 цифр',
    'form.invalid_ogrn': 'ОГРН должен содержать 15 цифр',
    'form.invalid_bik': 'БИК должен содержать 9 цифр',
    'form.invalid_account': 'Номер счета должен содержать 20 цифр',
    'form.validation_error': 'Исправьте ошибки валидации',
    'form.enter_advertiser_name': 'Введите название рекламодателя',
    'form.enter_legal_name': 'Введите юридическое название',
    'form.enter_contract_number': 'Введите номер договора',
    'form.enter_legal_address': 'Введите юридический адрес',
    'form.enter_description': 'Введите описание',
    'form.enter_adgroup_name': 'Введите название группы объявлений',
    'form.enter_creative_title': 'Где лучше тусовать...',
    'form.enter_creative_text': 'Килограммы денег просто так...',
    'form.period': 'Период',
    'form.creative_notice': 'Обратите внимание, что все созданные объявления будут рассмотрены модерацией.',
    'form.note_creative': 'Рекомендации по креативам',
    'form.creative_requirements': 'Все креативные материалы будут проверены в соответствии с нашими стандартами качества.',
    'form.small_format_desc': 'Малый формат для компактного размещения',
    'form.big_format_desc': 'Большой формат для максимальной видимости',
    'form.ad_groups': 'Группы объявлений',
    'form.all_day': 'Весь день',
    'action.exit': 'Выход',
    
    // Time periods
    'time.day': 'День',
    'time.week': 'Неделя',
    'time.month': 'Месяц',
    'time.whole_campaign': 'Вся кампания',
    
    // Additional statuses
    'status.pending': 'На модерации',
    'status.rejected': 'Отклонена',
    
    // Additional UI elements
    'nav.statistics': 'Статистика',
    'ui.all_formats': 'Все форматы',
    'ui.upload_creative': 'Загрузить креатив',
    'ui.grid_view': 'Сетка',
    'ui.chart_view': 'График',
    'ui.toggle_view': 'Переключить между сеткой и графиком',
    'ui.filter': 'Фильтр',
    'ui.apply_filter': 'Применить фильтры к результатам',
    'ui.search': 'Поиск',
    'ui.export': 'Экспорт данных',
    'ui.refresh': 'Обновить данные',
    'ui.view_all': 'Показать все',
    'ui.show_more': 'Показать больше',
    'ui.show_less': 'Показать меньше'
  }
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en' as Language,
      
      setLanguage: (language: Language) => {
        set({ language })
      },
      
      t: (key: string, fallback?: string) => {
        const { language } = get()
        const translation = (translations as any)[language]?.[key]
        return translation || fallback || key
      }
    }),
    {
      name: 'language-storage'
    }
  )
)
