import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'en' | 'ru'

interface LanguageState {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, fallback?: string) => string
}

// Переводы (технические термины оставляем на английском)
const translations = {
  en: {
    // Navigation
    'nav.main': 'Main',
    'nav.segments': 'Segments',
    'nav.dsp_analytics': 'DSP Analytics',
    'nav.advertisers': 'Advertisers',
    'nav.adgroups': 'Ad Groups',
    'nav.analytics': 'Analytics',
    'nav.fraud_detection': 'Fraud Detection',
    'nav.audience_insights': 'Audience Insights', 
    'nav.creative_performance': 'Creative Performance',
    'nav.campaigns': 'Campaigns',
    'nav.audiences': 'Audiences',
    'nav.creatives': 'Creatives',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    
    // Headers
    'header.dsp_analytics': 'DSP Analytics',
    'header.campaign_management': 'Campaign Management',
    'header.audience_insights': 'Audience Insights',
    'header.fraud_detection': 'Fraud Detection',
    'header.real_time': 'Real-time',
    'header.dsp_manager': 'DSP Manager',
    
    // Analytics Page
    'analytics.title': 'DSP Performance Dashboard',
    'analytics.total_impressions': 'Total Impressions',
    'analytics.total_clicks': 'Total Clicks',
    'analytics.average_ctr': 'Average CTR',
    'analytics.vs_last_week': 'vs last week',
    'analytics.device_performance': 'Device Performance',
    'analytics.top_regions': 'Top Regions',
    'analytics.real_time_bidding': 'Real-time Bidding',
    'analytics.bids_per_sec': 'Bids/sec',
    'analytics.win_rate': 'Win Rate %',
    'analytics.avg_price': 'Avg Price',
    'analytics.dsp_performance_metrics': 'DSP Performance Metrics',
    'analytics.campaign_team': 'Campaign Team',
    'analytics.active_campaigns_performance': 'Active Campaigns Performance',
    'analytics.export': 'Export',
    'analytics.status': 'Status',
    'analytics.impressions': 'Impressions',
    'analytics.clicks': 'Clicks',
    'analytics.conversions': 'Conversions',
    'analytics.spend': 'Spend',
    'analytics.active': 'Active',
    'analytics.paused': 'Paused',
    
    // Fraud Detection
    'fraud.title': 'Fraud Detection Center',
    'fraud.subtitle': 'Real-time traffic quality monitoring',
    'fraud.fraud_rate': 'Fraud Rate',
    'fraud.blocked_traffic': 'Blocked Traffic',
    'fraud.suspicious_ips': 'Suspicious IPs',
    'fraud.bot_traffic': 'Bot Traffic',
    'fraud.vs_yesterday': 'vs yesterday',
    'fraud.real_time_threats': 'Real-time Threats',
    'fraud.geographic_risk': 'Geographic Risk',
    'fraud.detection_methods': 'Detection Methods',
    'fraud.fraud_detection_log': 'Fraud Detection Log',
    'fraud.export_report': 'Export Report',
    'fraud.timestamp': 'Timestamp',
    'fraud.threat_type': 'Threat Type',
    'fraud.source_ip': 'Source IP',
    'fraud.campaign': 'Campaign',
    'fraud.severity': 'Severity',
    'fraud.action': 'Action',
    'fraud.status': 'Status',
    'fraud.high': 'High',
    'fraud.medium': 'Medium',
    'fraud.low': 'Low',
    'fraud.blocked': 'Blocked',
    'fraud.flagged': 'Flagged',
    'fraud.logged': 'Logged',
    'fraud.resolved': 'Resolved',
    'fraud.monitoring': 'Monitoring',
    'fraud.reviewed': 'Reviewed',
    
    // Audience Insights
    'audience.title': 'Audience Insights',
    'audience.subtitle': 'Deep audience analysis and segmentation',
    'audience.all_segments': 'All Segments',
    'audience.create_segment': 'Create Segment',
    'audience.high_value_customers': 'High-Value Customers',
    'audience.lookalike_audience': 'Lookalike Audience',
    'audience.retargeting_pool': 'Retargeting Pool',
    'audience.interest_based': 'Interest-Based',
    'audience.growth': 'Growth',
    'audience.conv_rate': 'Conv Rate',
    'audience.demographics': 'Demographics',
    'audience.age_groups': 'Age Groups',
    'audience.gender_split': 'Gender Split',
    'audience.female': 'Female',
    'audience.male': 'Male',
    'audience.top_interests': 'Top Interests',
    'audience.device_usage': 'Device Usage',
    'audience.devices': 'Devices',
    'audience.high_engagement': 'High engagement',
    'audience.medium_engagement': 'Medium engagement',
    'audience.low_engagement': 'Low engagement',
    'audience.operating_systems': 'Operating Systems',
    'audience.purchase_intent_analysis': 'Purchase Intent Analysis',
    'audience.average_intent_score': 'Average Intent Score',
    'audience.lookalike_performance': 'Lookalike Performance',
    'audience.quality_score': 'Quality Score',
    
    // Creative Performance
    'creative.title': 'Creative Performance',
    'creative.subtitle': 'Analyze and optimize creative assets',
    'creative.all_formats': 'All Formats',
    'creative.banner': 'Banner',
    'creative.video': 'Video',
    'creative.native': 'Native',
    'creative.display': 'Display',
    'creative.upload_creative': 'Upload Creative',
    'creative.total_creatives': 'Total Creatives',
    'creative.active': 'Active',
    'creative.avg_ctr': 'Avg CTR',
    'creative.top_ctr': 'Top CTR',
    'creative.avg_conv_rate': 'Avg Conv Rate',
    'creative.this_week': 'this week',
    'creative.of_total': 'of total',
    'creative.improvement': 'improvement',
    'creative.vs_last_month': 'vs last month',
    'creative.video_format': 'Video format',
    'creative.format_performance': 'Format Performance',
    'creative.active_ab_tests': 'Active A/B Tests',
    'creative.creative_assets': 'Creative Assets',
    'creative.export': 'Export',
    'creative.type': 'Type',
    'creative.performance': 'Performance',
    'creative.high': 'High',
    'creative.medium': 'Medium',
    'creative.low': 'Low',
    'creative.confidence': 'confidence',
    'creative.winner': 'Winner',
    
    // Common
    'common.campaign': 'Campaign',
    'common.campaigns': 'Campaigns',
    'common.name': 'Name',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.paused': 'Paused',
    'common.share': 'share',
    'common.engagement': 'engagement',
    'common.baseline': 'Baseline',
    'common.updated': 'Updated',
    'common.ago': 'ago',
    'common.min_ago': 'min ago',
    'common.day_ago': 'day ago',
    'common.vs': 'vs',
    'common.target': 'Target',
    'common.current': 'Current',
    'common.last_week': 'Last Week',
    'common.users': 'users',
    'common.impressions': 'impressions',
    'common.of_fraud': 'of fraud',
    'common.learning': 'Learning',
    'common.accuracy': 'Accuracy',
    
    // Settings
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.notifications': 'Notifications',
    'settings.profile': 'Profile',
    'settings.logout': 'Logout',
    'settings.english': 'English',
    'settings.russian': 'Русский',
    
    // Time ranges
    'time.1h': '1h',
    'time.6h': '6h', 
    'time.24h': '24h',
    'time.7d': '7d',
    'time.30d': '30d',
    'time.90d': '90d'
  },
  ru: {
    // Navigation
    'nav.main': 'Основные',
    'nav.segments': 'Сегменты',
    'nav.dsp_analytics': 'DSP Аналитика',
    'nav.advertisers': 'Рекламодатели',
    'nav.adgroups': 'Группы объявлений',
    'nav.analytics': 'Общая аналитика',
    'nav.fraud_detection': 'Детекция фрода',
    'nav.audience_insights': 'Анализ аудитории',
    'nav.creative_performance': 'Эффективность креативов',
    'nav.campaigns': 'Кампании',
    'nav.audiences': 'Аудитории',
    'nav.creatives': 'Креативы',
    'nav.reports': 'Отчёты',
    'nav.settings': 'Настройки',
    
    // Headers
    'header.dsp_analytics': 'DSP Аналитика',
    'header.campaign_management': 'Управление кампаниями',
    'header.audience_insights': 'Анализ аудитории',
    'header.fraud_detection': 'Детекция фрода',
    'header.real_time': 'Реальное время',
    'header.dsp_manager': 'DSP Менеджер',
    
    // Analytics Page
    'analytics.title': 'Панель эффективности DSP',
    'analytics.total_impressions': 'Всего показов',
    'analytics.total_clicks': 'Всего кликов',
    'analytics.average_ctr': 'Средний CTR',
    'analytics.vs_last_week': 'к прошлой неделе',
    'analytics.device_performance': 'Эффективность устройств',
    'analytics.top_regions': 'Топ регионы',
    'analytics.real_time_bidding': 'Биддинг в реальном времени',
    'analytics.bids_per_sec': 'Ставок/сек',
    'analytics.win_rate': 'Процент побед',
    'analytics.avg_price': 'Средняя цена',
    'analytics.dsp_performance_metrics': 'Метрики эффективности DSP',
    'analytics.campaign_team': 'Команда кампаний',
    'analytics.active_campaigns_performance': 'Эффективность активных кампаний',
    'analytics.export': 'Экспорт',
    'analytics.status': 'Статус',
    'analytics.impressions': 'Показы',
    'analytics.clicks': 'Клики',
    'analytics.conversions': 'Конверсии',
    'analytics.spend': 'Потрачено',
    'analytics.active': 'Активна',
    'analytics.paused': 'Приостановлена',
    
    // Fraud Detection
    'fraud.title': 'Центр детекции фрода',
    'fraud.subtitle': 'Мониторинг качества трафика в реальном времени',
    'fraud.fraud_rate': 'Доля фрода',
    'fraud.blocked_traffic': 'Заблокированный трафик',
    'fraud.suspicious_ips': 'Подозрительные IP',
    'fraud.bot_traffic': 'Ботовый трафик',
    'fraud.vs_yesterday': 'к вчерашнему дню',
    'fraud.real_time_threats': 'Угрозы в реальном времени',
    'fraud.geographic_risk': 'Географические риски',
    'fraud.detection_methods': 'Методы детекции',
    'fraud.fraud_detection_log': 'Журнал детекции фрода',
    'fraud.export_report': 'Экспорт отчёта',
    'fraud.timestamp': 'Время',
    'fraud.threat_type': 'Тип угрозы',
    'fraud.source_ip': 'Исходный IP',
    'fraud.campaign': 'Кампания',
    'fraud.severity': 'Серьёзность',
    'fraud.action': 'Действие',
    'fraud.status': 'Статус',
    'fraud.high': 'Высокий',
    'fraud.medium': 'Средний',
    'fraud.low': 'Низкий',
    'fraud.blocked': 'Заблокирован',
    'fraud.flagged': 'Отмечен',
    'fraud.logged': 'Записан',
    'fraud.resolved': 'Решён',
    'fraud.monitoring': 'Мониторинг',
    'fraud.reviewed': 'Проверен',
    
    // Audience Insights
    'audience.title': 'Анализ аудитории',
    'audience.subtitle': 'Глубокий анализ и сегментация аудитории',
    'audience.all_segments': 'Все сегменты',
    'audience.create_segment': 'Создать сегмент',
    'audience.high_value_customers': 'Высокоценные клиенты',
    'audience.lookalike_audience': 'Похожая аудитория',
    'audience.retargeting_pool': 'Пул ретаргетинга',
    'audience.interest_based': 'По интересам',
    'audience.growth': 'Рост',
    'audience.conv_rate': 'Конв. ставка',
    'audience.demographics': 'Демография',
    'audience.age_groups': 'Возрастные группы',
    'audience.gender_split': 'Распределение по полу',
    'audience.female': 'Женщины',
    'audience.male': 'Мужчины',
    'audience.top_interests': 'Топ интересы',
    'audience.device_usage': 'Использование устройств',
    'audience.devices': 'Устройства',
    'audience.high_engagement': 'Высокая активность',
    'audience.medium_engagement': 'Средняя активность',
    'audience.low_engagement': 'Низкая активность',
    'audience.operating_systems': 'Операционные системы',
    'audience.purchase_intent_analysis': 'Анализ намерений покупки',
    'audience.average_intent_score': 'Средний балл намерений',
    'audience.lookalike_performance': 'Эффективность похожих',
    'audience.quality_score': 'Оценка качества',
    
    // Creative Performance
    'creative.title': 'Эффективность креативов',
    'creative.subtitle': 'Анализ и оптимизация креативных материалов',
    'creative.all_formats': 'Все форматы',
    'creative.banner': 'Баннер',
    'creative.video': 'Видео',
    'creative.native': 'Нативная',
    'creative.display': 'Дисплей',
    'creative.upload_creative': 'Загрузить креатив',
    'creative.total_creatives': 'Всего креативов',
    'creative.active': 'Активные',
    'creative.avg_ctr': 'Средний CTR',
    'creative.top_ctr': 'Лучший CTR',
    'creative.avg_conv_rate': 'Средняя конв. ставка',
    'creative.this_week': 'на этой неделе',
    'creative.of_total': 'от общего',
    'creative.improvement': 'улучшение',
    'creative.vs_last_month': 'к прошлому месяцу',
    'creative.video_format': 'Видео формат',
    'creative.format_performance': 'Эффективность форматов',
    'creative.active_ab_tests': 'Активные A/B тесты',
    'creative.creative_assets': 'Креативные материалы',
    'creative.export': 'Экспорт',
    'creative.type': 'Тип',
    'creative.performance': 'Эффективность',
    'creative.high': 'Высокая',
    'creative.medium': 'Средняя',
    'creative.low': 'Низкая',
    'creative.confidence': 'достоверность',
    'creative.winner': 'Победитель',
    
    // Common
    'common.campaign': 'Кампания',
    'common.campaigns': 'Кампании',
    'common.name': 'Название',
    'common.status': 'Статус',
    'common.active': 'Активна',
    'common.paused': 'Приостановлена',
    'common.share': 'доля',
    'common.engagement': 'активность',
    'common.baseline': 'Базовая линия',
    'common.updated': 'Обновлено',
    'common.ago': 'назад',
    'common.min_ago': 'мин назад',
    'common.day_ago': 'день назад',
    'common.vs': 'к',
    'common.target': 'Цель',
    'common.current': 'Текущий',
    'common.last_week': 'Прошлая неделя',
    'common.users': 'пользователи',
    'common.impressions': 'показы',
    'common.of_fraud': 'фрода',
    'common.learning': 'Обучение',
    'common.accuracy': 'Точность',
    
    // Settings
    'settings.language': 'Язык',
    'settings.theme': 'Тема',
    'settings.notifications': 'Уведомления',
    'settings.profile': 'Профиль',
    'settings.logout': 'Выйти',
    'settings.english': 'English',
    'settings.russian': 'Русский',
    
    // Time ranges
    'time.1h': '1ч',
    'time.6h': '6ч',
    'time.24h': '24ч', 
    'time.7d': '7д',
    'time.30d': '30д',
    'time.90d': '90д'
  }
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en' as Language,
      
      setLanguage: (language: Language) => {
        set({ language })
      },
      
      t: (key: string, fallback?: string) => {
        const { language } = get()
        const translation = (translations as any)[language]?.[key]
        return translation || fallback || key
      }
    }),
    {
      name: 'language-storage'
    }
  )
)
